# Clone the repos we want to use
resources:
  repositories:

  - repository: InvisibilityCloak
    type: github
    endpoint: castlocal8
    name: castlocal8/InvisibilityCloak

  - repository: SeatBelt
    type: github
    endpoint: castlocal8
    name: castlocal8/Seatbelt

trigger:
- main

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
